### ISSUE TITLE
2019年9月版本迭代需求

### ISSUE THREAD

**Issue by 2903710916** [muxiangqiu/malagu#1]
1. deploy命令改进支持多云扩展定制  P0
a. 支持每个云平台一个部署插件独立实现
b. 公共的入口适配逻辑可由各个插件扩展定制
c. 阿里云的fc-adapter发布配置支持优先使用项目配置覆盖fun config生成的全局配置

2. mono repo应用工程模板 P1
a. malagu插件规范定义文档
b. 支持到init的官方模板中命名为monorepo
c. 支持npm包的标准发布内置并且支持私有源的更换的配置

3. RPC的返回类型支持用户自动以扩展 P0
例如，html返回和jsonp返回等等。可以暂时通过业务完善中间件机制实现，后续这部分实现要成为框架底层标准部分。

4. 数据库访问方案集成 P3
业务暂时集成typeorm或prisma使用，后续考虑在框架层面上优化支持。

5. 支持用户自定义请求路由待测试验证。P0

6. typescript的reactjs的前端开发框架的集成。P1
类的reactjs的组件已经可以支持，对函数式组件的集成待设计。

7. RPC的请求错误规范的定义。P1

**Comment by 2903710916** [comment]
配置模块的问题汇总

app.yml和app-*.yml的配置文件，在本地调试的时候，修改配置信息后无法自动实时生效，需要支持webpack上后端打包的时候watch进去。P2

**Comment by 2903710916** [comment]
开发调试和发布监控相关问题汇总 （开发体验和线上质量相关高优先级）

1. RPC的异常处理和前后端的错误规范约定。P0
   需要支持底层框架上各种用户异常都可以正确的服务端返回不会出现请求超时，异常的错误码应该有一套规范进行约束定义并且可以正确的透传到前端去与前端错误处理机制无缝衔接上，对于非前后端一体化的项目可以自动导出SDK的接口给到其他前端项目中使用。
2.日志方案设计。 P1
3.监控报警方案设计。 P1
4.多环境发布方案设计。 P1
5.本地单步调试vscode的工具配置文档说明。P1
6.本地调试支持可配使用http的entry而不是websocket的entry。 P0 （用于支持非前后端一体化前端部分的开发联调集成）
7.本地webpack的devserver的proxy方案的完整设计方案。P2 （可以暂时在服务端配置CORS跨域解决此问题）
8.服务端的CORS跨域的完整设计方案支持。P2

**Comment by 2903710916** [comment]
前端联调相关的对接需求汇总

1. 支持自定义路由返回html或json的注解  P0

**Comment by 2903710916** [comment]
在FaaS上做纯后端单体应用开发的普适业务场景需求：

在中后台业务场景下和大量中小项目中单体应用基本上都是单体应用开发模式为主，FaaS时代之前主要开发模式都是基于LSB+ECS的运维特点上形成的PHP和JAVA两大类型Web应用开发框架为主以及少量NodeJS为辅，FaaS的运维特点天生就适合NodeJS开发（相关内部数据基本上可以证明NodeJS已经是FaaS上的第一开发框架），但是NodeJS的现有框架设计达到PHP和JAVA做单体Web应用一样的技术框架成熟度根本做不了相对复杂的应用。要想推动FaaS的快速普及，目前来看业界最缺的就是缺少一套为FaaS量身定制将其潜能充分发挥的并且吸收大量前端工程优秀思想同时又继承了PHP和JAVA的Web开发框架设计精髓的更加高级的新一代NodeJS普适Web开发框架。一旦这个框架做出来并且由社区主导不断地演进迭代优化势必会推动FaaS云产品的全面业界普及，并且有助于FaaS之上的外围生态的快速孵化产生。

malagu现有设计改进优化点：
1. 再设计一个纯后端开发的模板将browser部分全部去掉，参照PHP和JAVA的纯后端单体应用的设计理念搭建基础应用开发框架。
2. 在服务与函数的基础上抽象出应用维度的概念屏蔽掉底层云厂商维度的运维概念，并将应用创建、更新、发布、灰度、下线、资源申请绑定配置、开发调试等应用的全生命周期的管理覆盖到融入到新框架设计上。
3. 路由、cookie、session、controller、view、middleware等Web应用通用概念应该继承PHP和JAVA等相关框优秀设计理念融入到FaaS NodeJS开发框架上集大成。
4. TypeORM数据库的相关优化设计。这是NodeJS各种已有Web开发框架的短板。
5. 结合npm包的特点设计后端应用开放插件体系。
6. 发挥NodeJS可以无缝衔接前端的语言优势在BFF层上进行精心设计。
7. 经过安全评审确保架构设计上无不安全设计。

总结，FaaS NodeJS新一代Web应用开发框架应该是革命性的设计，如同jquery开发过渡到reactjs和vuejs开发类似的技术演进过程，现阶段的主要应用人群应该是传统web应用后端开发者。

**Comment by creamidea** [comment]
这些需求目前进展如何？

**Comment by muxiangqiu** [comment]
已经完成
